### ISSUE TITLE
Can aggregateBy be index instead of timeline?

### ISSUE THREAD

**Issue by MeSawSomething** [walterra/react-milestones-vis#4]
Hi. Walter. love your work!
My current project needs to show milestone per index, which shows from 0 and goes up to 120,000.
There's a range property but once I input the year data, it shows '1970', which probably meaning it doesn't recognize.

Cheers!

**Comment by walterra** [comment]
Thanks for the nice feedback! Can you share a sample of the data and d3-milestones configuration you're using, this will make it easier for me to reproduce, will then try to come up with a solution.

**Comment by MeSawSomething** [comment]
Actually I sorted it out by dividing the index actually :) sorry for wrapping over another issue here, but do you have any plan to support react 18v?

**Comment by MeSawSomething** [comment]
I will close this issue as last inquiry enrolled as an new issue #5
